### ISSUE TITLE
com.github.baloise:rocket-chat-rest-client:jar:0.1.2-SNAPSHOT is missing

### ISSUE THREAD

**Issue by nephilimboy** [baloise/rocket-chat-rest-client#16]
I got this error on eclipse with maven : 
The POM for com.github.baloise:rocket-chat-rest-client:jar:0.1.2-SNAPSHOT is missing, no dependency information available
my pom.xml :
-----------------------------------------------------------------------
  <repositories>
    <repository>
        <id>jitpack.io</id>
         <url>https://jitpack.io</url>
    </repository>
</repositories>

  <dependencies>
  
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    
    
    <dependency>
        <groupId>com.github.baloise</groupId>
        <artifactId>rocket-chat-rest-client</artifactId>
        <version>0.1.2-SNAPSHOT</version>
    </dependency>
  </dependencies>
-----------------------------------------------------------------
its like no repo is available. 
Thanks in advance.

**Comment by graywolf336** [comment]
I'll work on this first thing Monday, the repository will change though and will contain a stable release along with a snapshot.

**Comment by nephilimboy** [comment]
thanks man, so ill wait until then

**Comment by graywolf336** [comment]
@nephilimboy Here you go, although be warned that the current state of the methods and api is changing rapidly until we get to a stable version. So, be prepared for things to suddenly change before we release `0.2.0`.

```xml
<repositories>
    <repository>
        <id>repo-snapshots</id>
        <url>https://repo.craftyn.com/repository/snapshots/</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>com.github.baloise</groupId>
        <artifactId>rocket-chat-rest-client</artifactId>
        <version>0.1.2-SNAPSHOT</version>
    </dependency>
</dependencies>
```

**Comment by nephilimboy** [comment]
Great,,,, I'm looking forward to it,,,

**Comment by graywolf336** [comment]
@nephilimboy It is up now, so it should be working. Let me know if it doesn't or if you have issues. :+1:

**Comment by CarlosEduR** [comment]
Hi, guys! I'm having some problem with this dependency. I've added repository tag and dependecy tag, but it just returns 'com.github.baloise:rocket-chat-rest-client:jar:0.1.2-SNAPSHOT not found.'.
