### ISSUE TITLE
repository wildcard cert has expired

### ISSUE THREAD

**Issue by maxfieb** [baloise/rocket-chat-rest-client#23]
FYI the wildcard cert on https://repo.craftyn.com/repository/snapshots/ is invalid (cert expired)

Common Name (CN)	*.craftyn.com
Organisation (O)	<Not Part Of Certificate>
Organisational Unit (OU)	Domain Control Validated
Common Name (CN)	COMODO RSA Domain Validation Secure Server CA
Organisation (O)	COMODO CA Limited
Organisational Unit (OU)	<Not Part Of Certificate>
Issued On	Tuesday, 20 January 2015 at 10:00:00
Expires On	Wednesday, 21 March 2018 at 09:59:59

Simple solution might be to use http:// instead of https:// but the server always redirects to SSL.

Various "dont check ssl" maven options dont seem to work in maven 3.5.3

**Comment by graywolf336** [comment]
The ssl has been ordered, I'm just needing to finish the process. My apologies

**Comment by maxfieb** [comment]
no big. i thought i should at least mention it as sometimes people dont :)

**Comment by graywolf336** [comment]
Closing as I finally was able to get things going again. :)
