### ISSUE TITLE
Please allow squash commit merging

### ISSUE THREAD

**Issue by col-panic** [baloise/rocket-chat-rest-client#44]
Hey owners, could you please allow squash commit merging for this repo? See https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests thanks!

**Comment by MarkusTiede** [comment]
Already set - please check whether it works as expected:

![image](https://user-images.githubusercontent.com/1764012/70418076-f81d2c00-1a62-11ea-937d-b88733e176c7.png)

**Comment by col-panic** [comment]
@MarkusTiede thanks I found it! I though it has to be activated on creating the PR :)
