### ISSUE TITLE
Certificated expired

### ISSUE THREAD

**Issue by Canos** [baloise/rocket-chat-rest-client#58]
I hope you all were safe and sound.

Can you renew the ssl certificate, it's expired since yesterday and some of our buildings are failing.

**Comment by col-panic** [comment]
What certificate do you mean? Which url?

**Comment by Canos** [comment]
The one who host the project:
https://repo.craftyn.com/repository/snapshots/

Can you upload the project to Maven Central?

**Comment by col-panic** [comment]
Sorry, this project does not manage craftyn.com - so there is nothing we can do. 
Creating a new release is handled in #46

**Comment by Canos** [comment]
Ok, well, maybe it's a good time to do the change. 
Everyone CI pipelines are suppose to be broken.
