### ISSUE TITLE
Direct message api was not found.

### ISSUE THREAD

**Issue by salviof** [baloise/rocket-chat-rest-client#61]
Has low documentation about how sent direct message in rest api. 
I not found how to do this with this project.

**Comment by col-panic** [comment]
The respective test in https://github.com/baloise/rocket-chat-rest-client/blob/39d7dea7b4aeb3c3f3d64238122dbea9dd47b989/src/test/java/com/github/baloise/rocketchatrestclient/RocketChatClientChatTestIT.java#L27 does document on how to send a direct message.
